/**
 * @description       : 
 * @author            : Girish Kalidindi
 * @group             : 
 * @last modified on  : 04-08-2021
 * @last modified by  : Girish Kalidindi
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   04-05-2021   Girish Kalidindi   Initial Version
**/
public class DRB2B_ApplicationConstants {

    // Webhook Constants
    public static final String WEBHOOK_DEFAULT_HANDLER_CONFIG_NAME = 'default_handler';

    // Http Status Codes
    public static final Integer SUCCESS_RESPONSE_CODE = 200;
    public static final Integer ERROR_RESPONSE_CODE = 400;

}